# Generated by Django 2.1 on 2019-06-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='published_date',
        ),
    ]
